### ISSUE TITLE
Enhancement: Add recaptcha to mailout form

### ISSUE THREAD

**Issue by hdrlab** [SchumacherFM/mailout#1]
Having the ability to add a recaptcha to the form would help protect against spam bots. 

I spotted a Go recaptcha lib, so perhaps that could be used as a starting point:
https://github.com/dpapathanasiou/go-recaptcha

**Comment by SchumacherFM** [comment]
Would you like to implement it?

**Comment by SchumacherFM** [comment]
I received the first spam email:

> email_org:   [jesse_millea36@rambler.ru]
> name:   [CS Web Contact Form]
> submit:   [Send message]
> url:   [http://www.google.com]
> Best regards!
> 
> RemoteAddr: 91.79.9.XXX:58149
> Browser: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36

If it increases then I'll add probably a captcha feature ...

Please also post here if you (dear reader of this issue) are also affected.

**Comment by hdrlab** [comment]
When I wrote this suggestion I was considering replacing my website with Caddy + Hugo, but ended up sticking with Silverstripe instead (even though I don't like PHP). So this issue doesn't affect me.

I still think that some sort of anti-spam feature like recaptcha is a good idea, though.

**Comment by mholt** [comment]
@hdrlab Slightly off topic, but is there a reason you went with Silverstripe instead? We'd like Caddy and its hugo add-on to be competitive as much as possible :smile:

**Comment by hdrlab** [comment]
@mholt A few reasons:
- I'm familiar with Silverstripe
- I really do prefer editing pages using a WYSIWYG editor
- Silverstripe also handles stuff like generating scaled images automatically, which I think is on Hugo's roadmap, but isn't there yet
- Silverstripe has a static caching/export module, allowing you to mix the speed of static pages with the flexibility of a CMS. That's the main drawcard of a static site generator like Hugo taken care of
- At some point the website may have multiple contributors, and having to train others to use markdown, etc., would be a bit of a barrier
- IIRC, the Hugo plugin uses basic HTTP auth., which is rather clunky. This is a minor point, but adding users and setting permissions in a CMS is much easier

**Comment by mholt** [comment]
Thank you for the feedback @hdrlab! We'll look into it.

**Comment by lexesv** [comment]
@mholt  Hi, mailout+captcha https://github.com/lexesv/mailout

**Comment by SchumacherFM** [comment]
@lexesv Wow! Looks good. If you want you can send me a pull request and I merge it and propagate it to the caddy plugin registry. I can also give you contributor access to this repo so that you can directly commit stuff. One thing which can be improved in your commits is a bit more descriptive commit message ;-)

**Comment by lexesv** [comment]
@SchumacherFM Hi, thanks.
I plan to add the reCaptcha support and then send a pull request.

**Comment by SchumacherFM** [comment]
Fixed with PR #16
