### ISSUE TITLE
Mailout is not mailing out

### ISSUE THREAD

**Issue by arthurpro** [SchumacherFM/mailout#2]
Hi Schumacher,

Your plugin looks really good and has lots of cool features.
But, it is not sending anything.
I tried all possible configs and 3 different smtp servers with all possible ports etc
Nothing was sent and all mailout logs are just empty.
Also I tried running it on Mac as well as on CentOS.
Are you aware of the issue?

**Comment by SchumacherFM** [comment]
No. How should I debug that?

**Comment by arthurpro** [comment]
I'm using the latest build of Caddy. Just very basic setup.
Here is my Caddyfile

```
:2020

root public

log log/access.log
errors log/error.log

header / -Server

mailout /mailout {
    maillog log/mail
    errorlog log/mail

    to "mail@xxxxxxxx.com"
    subject "Email from {{.Form.Get \"name\"}}"
    body mailout.html

    username "xxxxx"
    password "xxxxx"
    host xxxx
    port 25
}
```
As I mentioned before I tried multiple SMTP servers including Gmail.
Nothing goes through. /mailout URL returns success.
In the log dir I have the following files which are empty
```
-rw------- 1 xxxx xxxxx 0 Mar 15 21:09 mail_2020_1458090563473784478.txt
-rw------- 1 xxxx xxxxx 0 Mar 15 21:49 mail_2020_1458092980691427299.txt
-rw------- 1 xxxx xxxxx 0 Mar 15 21:08 mail_errors_2020.log
```
I tried both txt and html templates. Same problem with both.
Any idea?

**Comment by SchumacherFM** [comment]
What is your OS?
I'll test your config this week on my MacBook.
Can you try to use a full path for maillog and errorlog?

**Comment by arthurpro** [comment]
I tried it on Mac OS 10.10 and on CentOS 6.7
On Mac I also used MailHog to debug the problem.
What I could see is that Mailout would connect to smtp, authenticate and then it does nothing.
It never sends anything.
And yes, I tried using full path for the logs, same problem.

**Comment by SchumacherFM** [comment]
I can confirm that there is a bug. For my 2nd domain and 2nd mailout configuration no mail gets send out and neither does it gets saved into a file.

The 1st domain with the 1st mailout config works as expected.

I hope I get that fixed this week.

**Comment by arthurpro** [comment]
Great you were able to reproduce.
Let me know if you need any help.

**Comment by sapiens-sapide** [comment]
Hello, 
same issue for me on freeBSD.
Here is my CaddyFile :

      sapienssapide.com {
	root /usr/local/www/sapienssapide.com/public
	
         (………)

	mailout /contact {
		maillog		/var/log/caddy-mailout.log
		errorlog	/var/log/caddy-mailout.log

		to xxxx@xxxxx.xxx
		subject "Email depuis formulaire de contact de sapienssapide.com"
		body /usr/local/www/contact-mailout-template.txt

		username "xxxx@xxxxx"
		password "xxxxx"
		host "post.mailden.net"
		port 587
	}
}`

each time I fill the contact form on the website, I get back the 200 OK status code. But, an empty file is created in /var/log/caddy-mailout.log/ and nothing is sent. As far as I can see from my stmp server logs, an anonymous connection is made, but no authentification after that and nothing sent.

If I could help.
Regards,
Stan.

**Comment by SchumacherFM** [comment]
Still working on it and I can reproduce it.

**Comment by arthurpro** [comment]
Oneliner fix.
How awesome! :)

**Comment by SchumacherFM** [comment]
The bug is fixed. You can either self compile caddy or maybe @mholt knows if his build server is automatically pulling in the latest changes from this repo and then you can simply download your custom caddy build from https://caddyserver.com/download
But afaik there might be some caching involved.

**Comment by arthurpro** [comment]
I will recompile and test tomorrow to make sure it works.
But your fix looks good to me. Nice job!

**Comment by mholt** [comment]
@SchumacherFM It's not (that resulted in problems, of course) -- so I'll manually update, hmm, probably tomorrow.

**Comment by mholt** [comment]
Updated. Cheers!

**Comment by sapiens-sapide** [comment]
thanks, all folks !
