### ISSUE TITLE
Support non file based logging

### ISSUE THREAD

**Issue by stp-ip** [SchumacherFM/mailout#9]
Currently only file based logging is available. It would be awesome, if it supported stdout/stderr/syslog as caddy does.

Awesome plugin. Thanks

**Comment by SchumacherFM** [comment]
stdout/stderr seems possible. For syslog I have to dig around ;-)

**Comment by stp-ip** [comment]
I am happy with stdout and stderr, but it made sense to also mention syslog.

**Comment by SchumacherFM** [comment]
I'll test it now on production on my website and will report it later to mholt to update the plugin in the registry. But you can always compile it yourself into caddy ;-)

**Comment by stp-ip** [comment]
Awesome thanks. Will do my best to find some time to check it out. Will report back any findings.

**Comment by stp-ip** [comment]
Works perfectly thanks.
